#Game configuration
#Time to iniciate game(in minutes)
StartTime: 1
#Time of the fase(in minutes)
PhaseTimeOne: 8
PhaseTimeTwo: 8
PhaseTimeThree: 8
PhaseTimeFour: 8
#Team spawns
#Yellow spawn
YellowSpawnX: 0
YellowSpawnY: 0
YellowSpawnZ: 0
#Red spawn
RedSpawnX: 0
RedSpawnY: 0
RedSpawnZ: 0
#Green spawn
GreenSpawnX: 0
GreenSpawnY: 0
GreenSpawnZ: 0
#Blue spawn
BlueSpawnX: 0
BlueSpawnY: 0
BlueSpawnZ: 0
#lobby list
lobby-list:
 - world
 - annihilation
#arena list
arena-list:
 - annihilation_play
#no permission
NoPermission: "You don't have sufficient permissions to set spawn."
#Blocks to keep replacing (replaces every 30 seconds)
#Format = X:Y:Z:ID:DAMAGE:LEVEL
Blocks:
 - 99:99:99:1:0:annihilation
#Death message
#{ATTACKER} = killer
#{VICTIM} = death victim
PlayerDeathMessage: "{ATTACKER} killed {VICTIM}"
#Ammount of points gained per kill
GainedPoints: 1
#Message when player gets points
#{POINTS} = total points player has
#{GAINED} = gained points
GainedPointsMessage: "+ {GAINED} points!"
#Tell a player he/she cannot hit a team mate/friend
#{FRIEND} = team mate name
FriendlyAttackMessage: "You can't attack {FRIEND} because you are both on the same team!"
#When player join yellow, what message should be sent?
JoinedYellowMesage: "Welcome to yellow!"
  #To message hide set "Show" to "false"
  Show: true
#When player join red, what message should be sent?
JoinedRedMesage: "Welcome to red!"
  #To message hide set "Show" to "false"
  Show: true
#When player join green, what message should be sent?
JoinedGreenMesage: "Welcome to green!"
  #To message hide set "Show" to "false"
  Show: true
#When player join blue, what message should be sent?
JoinedBlueMesage: "Welcome to blue!"
  #To message hide set "Show" to "false"
  Show: true
