name: WhatsUp
version: Beta-1
main: WU\WU
api: 1.12.0
load: POSTWORLD

description: Custom status
author: Artide
website: N/A

commands:
  wu:
    description: "Set your custom status"
    permission: wu.wu
  ss:
    description: "Save your custom status"
    permission: wu.ss
  ds:
    description: "Delete your custom status"
    permission: wu.ds

permissions:
  wu.wu:
    default: true
    description: "Set your custom status"
  wu.ss:
    default: true
    description: "Save your status"
  wu.ds:
    default: true
    description: "Delete your status"
