---
#Warning: don't use @whats_up in Join_Format because @whats_up is only for unsaved status-
#and @saved_status is for saved status.
Format: "@player\n@rb@whats_up"
Join_Format: "@player\n@rb@saved_status"
...
